name: PR tests

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Rust toolchain 1.74 (with clippy and rustfmt)
      run: rustup toolchain install 1.74-x86_64-unknown-linux-gnu && rustup component add clippy --toolchain 1.74-x86_64-unknown-linux-gnu && rustup component add rustfmt --toolchain 1.74-x86_64-unknown-linux-gnu
    - name: Install pil-stark dependency
      run: sudo apt-get install -y nlohmann-json3-dev
    - name: Format
      run: cargo fmt --all --check --verbose
    - name: Lint
      run: cargo clippy --all --all-targets --all-features --profile pr-tests -- -D warnings
    - name: Build
      run: cargo build --all --all-targets --all-features --profile pr-tests
    - uses: taiki-e/install-action@nextest
    - name: Run tests
      run: RUST_LOG=info cargo nextest run --workspace --all-features --all-targets --cargo-profile pr-tests
